name: main

on: [push, pull_request]

jobs:
  check-codingstyle:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install clang-format-6.0
      - name: check coding style
        run: CLANG_FORMAT_CMD=clang-format-6.0 ci/check-codingstyle

  build:
    runs-on: ${{ matrix.os }}
    env:
      PYTHONUNBUFFERED: 1
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15
          - windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: ci/install-dependencies deps
        shell: bash
      - name: Build
        run: . deps/env.sh && ci/build-app
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: build/nanonote[-_]*.*
